language: python
sudo: false
matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial
      sudo: true
env:
  global:
    - secure: "fHTmXSkUyVFu7lJ4upcu4Xhv+5cTGq+SJ+GV9UUJ9guZYVWafxJw3CRmd/qqjucQzOTPg/2JA4/9XqDZDSWKKBwGTOgeiFjKaa4xPFO/bvpbECqR4y7TDh7k7zSjMCDD624b8k6LyWiaerh50ShU2CSi3cTjpyZWloolQWRotLM="
    - REPO: "ASPP/pelita"
# command to install dependencies
install:
  - pip install pytest-cov codecov coveralls
  - pip install -e .
# command to run tests
script:
  - >
      python -c "import zmq; print('Using pyzmq {} and zmq {}.'.format(zmq.pyzmq_version(), zmq.zmq_version()))" &&
      python -m pytest --cov=pelita -v test/ &&
      python -m pelita.scripts.pelita_main --progress &&
      pelita --null --rounds 100 --filter small $player 2>&1
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pelita-tournament --non-interactive --viewer null ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 || $TRAVIS_PYTHON_VERSION == 3.7 ]]; then git clone https://github.com/ASPP/pelita_template && cd pelita_template/ && python -m pytest . ; fi


after_success:
  - codecov
  - coveralls
  - ./deploy-gh-pages.sh
