language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "pip install pyzmq --use-mirrors"
# command to run tests
script: nosetests -v && ./pelitagame --progress --publish tcp://*:*
